# Generated by Django 4.0.1 on 2022-01-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_rename_user_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Users',
        ),
    ]
